<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Toplu PDF Yazdirici</AssemblyName>
    <Version>1.1.0</Version>
    <Product>ASCOS PrintHub</Product>
    <Company>ASCOS</Company>
    <TargetPlatformMoniker>Windows,Version=7.0</TargetPlatformMoniker>
    <ApplicationIcon>ascos-printhub-web-clean.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="SumatraPDF.exe" LogicalName="ASCOS.PrintHub.SumatraPDF.exe" />
  </ItemGroup>
</Project>
